liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  #driver: "gd"
  resolvers:

    default:
      web_path: ~
  #                web_root: "%kernel.project_dir%/.."
  #                cache_prefix: "media/cache"

  # define your filter sets under this option
  filter_sets:
    cache: ~
    image_88_88:
      quality: 80
      filters:
        resize:
          size: [88, 88]

    image_190_143:
      quality: 80
      filters:
        resize:
          size: [190, 143]

    image_230_140:
      quality: 80
      filters:
        resize:
          size: [230, 140]

    image_263_200:
      quality: 80
      filters:
        resize:
          size: [263, 200]

    image_640_480:
      quality: 80
      filters:
        resize:
          size: [640, 480]


    image_1600_900:
      quality: 80
      filters:
        resize:
          size: [1600, 900]

#liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
#    # define your filter sets under this option
#    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#        squared_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
